[build-system]
requires = ["setuptools","wheel","cython"]
build-backend = "setuptools.build_meta"


[project]
name = "mypkg"
version = "0.0.1"

[tool.setuptools]
package-dir = {"" = "src"}
include-package-data = false

[tool.setuptools.packages.find]
where = ["src"]
